force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DishCategories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dish__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>Subcategory</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>DishSubcategories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DishCategories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Garnishes</fullName>
    </customValue>
    <customValue>
        <fullName>Main course</fullName>
    </customValue>
    <customValue>
        <fullName>Desserts</fullName>
    </customValue>
    <customValue>
        <fullName>Snacks</fullName>
    </customValue>
    <customValue>
        <fullName>Meaty</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable</fullName>
    </customValue>
    <customValue>
        <fullName>Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Soups</fullName>
    </customValue>
    <customValue>
        <fullName>Drinks</fullName>
    </customValue>
    <masterLabel>DishCategories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DishSubcategories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bread</fullName>
    </customValue>
    <customValue>
        <fullName>Biscuits</fullName>
    </customValue>
    <customValue>
        <fullName>Muffins</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable garnish</fullName>
    </customValue>
    <customValue>
        <fullName>Cereal garnish</fullName>
    </customValue>
    <customValue>
        <fullName>Fried dishes</fullName>
    </customValue>
    <customValue>
        <fullName>Stews dishes</fullName>
    </customValue>
    <customValue>
        <fullName>Baked dishes</fullName>
    </customValue>
    <customValue>
        <fullName>Sandwiches</fullName>
    </customValue>
    <customValue>
        <fullName>Paste</fullName>
    </customValue>
    <customValue>
        <fullName>Caviar</fullName>
    </customValue>
    <customValue>
        <fullName>Sneeks</fullName>
    </customValue>
    <customValue>
        <fullName>Canape</fullName>
    </customValue>
    <customValue>
        <fullName>Tartlets</fullName>
    </customValue>
    <customValue>
        <fullName>Threads</fullName>
    </customValue>
    <customValue>
        <fullName>Pickles</fullName>
    </customValue>
    <customValue>
        <fullName>Beef</fullName>
    </customValue>
    <customValue>
        <fullName>Chicken</fullName>
    </customValue>
    <customValue>
        <fullName>Pork</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Fried</fullName>
    </customValue>
    <customValue>
        <fullName>Boiled</fullName>
    </customValue>
    <customValue>
        <fullName>Stewed</fullName>
    </customValue>
    <customValue>
        <fullName>River fish</fullName>
    </customValue>
    <customValue>
        <fullName>Sea fish</fullName>
    </customValue>
    <customValue>
        <fullName>Seafood</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable</fullName>
    </customValue>
    <customValue>
        <fullName>Meaty</fullName>
    </customValue>
    <customValue>
        <fullName>Lungs</fullName>
    </customValue>
    <customValue>
        <fullName>Hot</fullName>
    </customValue>
    <masterLabel>DishSubcategories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DishesControllerTest.cls
@isTest
public with sharing class DishesControllerTest {
    
    public static String TEST_DISH_NAME = 'Test dish';
    public static String TEST_DISH_CATEGORY = 'Bakery';
    public static String TEST_DISH_SUBCATEGORY = 'Bread';

    public static String EXPECTED_NO_DISHES = 'Actual amount of dishes does not equal to excpected. (Expected 0)';
    public static String INVALID_AMOUNT = 'Actual amount of dishes does not equal to excpected';

    @isTest
    public static void testEmptyDishes() {

        List<Dish__c> dishes = DishesController.getMenu();

        System.assertEquals(0, dishes.size(), EXPECTED_NO_DISHES);
    }

    @isTest
    public static void testWithDishData() {

        List<Dish__c> dishes = new List<Dish__c>();
        Integer length = 5;

        for(Integer i = 1; i <= length; i++) {
            Dish__c dish = new Dish__c(Title__c = TEST_DISH_NAME,
                                       Category__c = TEST_DISH_CATEGORY,
                                       Subcategory__c = TEST_DISH_SUBCATEGORY,
                                       Price__c = i);
            dishes.add(dish);
        }

        insert dishes;

        List<Dish__c> resultDishes = DishesController.getMenu();
        System.assertEquals(length, resultDishes.size(), INVALID_AMOUNT); 
    }
}