force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish_Order__c/Dish_Order__c.object-meta.xml
<CustomObject>
    <label>Dish Order</label>
    <nameField>
        <label>Dish Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dish Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Comment_to_dish__c.field-meta.xml
<CustomField>
    <fullName>Comment_to_dish__c</fullName>
    <label>Comment to dish</label>
    <length>1500</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Dish_Order__c.field-meta.xml
<CustomField>
    <fullName>Dish_Order__c</fullName>
    <label>Dish Order</label>
    <referenceTo>Dish_Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Item_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_Price__c</fullName>
    <formula>Amount__c *  Dish__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DishOrderItemController.cls
public with sharing class DishOrderItemController {
    @AuraEnabled()
    public static List<Order_Item__c> getOrderItemsByOrderId(Id id) {
        List<Order_Item__c> items;

        try {
            items = [SELECT Dish__c, Dish_Order__c, Amount__c, Comment_to_dish__c, Item_Price__c
                    FROM Order_Item__c];
        } catch (System.QueryException queryException) {
            items = new List<Order_Item__c>();
        }

        return items;
    }

    @AuraEnabled(cacheable=true)
    public static List<Order_Item__c> getOrderItems(Id idddd) {
        List<Order_Item__c> items;

        System.debug(idddd);

        try {
            items = [SELECT Dish__c, Dish_Order__c, Amount__c, Comment_to_dish__c, Item_Price__c
                    FROM Order_Item__c ];
        } catch (System.QueryException queryException) {
            items = new List<Order_Item__c>();
        }

        return items;
    }

    @AuraEnabled(cacheable=true)
    public static Order_Item__c getOrderItemById(Id id) {
        return [SELECT Id, Dish__c, Dish_Order__c, Amount__c, Comment_to_dish__c, Item_Price__c
                FROM Order_Item__c WHERE Id = :id];
    }
}