force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DishCategories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dish__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dish__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>Subcategory</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>DishSubcategories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DishCategories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Garnishes</fullName>
    </customValue>
    <customValue>
        <fullName>Main course</fullName>
    </customValue>
    <customValue>
        <fullName>Desserts</fullName>
    </customValue>
    <customValue>
        <fullName>Snacks</fullName>
    </customValue>
    <customValue>
        <fullName>Meaty</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable</fullName>
    </customValue>
    <customValue>
        <fullName>Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Soups</fullName>
    </customValue>
    <customValue>
        <fullName>Drinks</fullName>
    </customValue>
    <masterLabel>DishCategories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DishSubcategories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bread</fullName>
    </customValue>
    <customValue>
        <fullName>Biscuits</fullName>
    </customValue>
    <customValue>
        <fullName>Muffins</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable garnish</fullName>
    </customValue>
    <customValue>
        <fullName>Cereal garnish</fullName>
    </customValue>
    <customValue>
        <fullName>Fried dishes</fullName>
    </customValue>
    <customValue>
        <fullName>Stews dishes</fullName>
    </customValue>
    <customValue>
        <fullName>Baked dishes</fullName>
    </customValue>
    <customValue>
        <fullName>Sandwiches</fullName>
    </customValue>
    <customValue>
        <fullName>Paste</fullName>
    </customValue>
    <customValue>
        <fullName>Caviar</fullName>
    </customValue>
    <customValue>
        <fullName>Sneeks</fullName>
    </customValue>
    <customValue>
        <fullName>Canape</fullName>
    </customValue>
    <customValue>
        <fullName>Tartlets</fullName>
    </customValue>
    <customValue>
        <fullName>Threads</fullName>
    </customValue>
    <customValue>
        <fullName>Pickles</fullName>
    </customValue>
    <customValue>
        <fullName>Beef</fullName>
    </customValue>
    <customValue>
        <fullName>Chicken</fullName>
    </customValue>
    <customValue>
        <fullName>Pork</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Fried</fullName>
    </customValue>
    <customValue>
        <fullName>Boiled</fullName>
    </customValue>
    <customValue>
        <fullName>Stewed</fullName>
    </customValue>
    <customValue>
        <fullName>River fish</fullName>
    </customValue>
    <customValue>
        <fullName>Sea fish</fullName>
    </customValue>
    <customValue>
        <fullName>Seafood</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable</fullName>
    </customValue>
    <customValue>
        <fullName>Meaty</fullName>
    </customValue>
    <customValue>
        <fullName>Lungs</fullName>
    </customValue>
    <customValue>
        <fullName>Hot</fullName>
    </customValue>
    <masterLabel>DishSubcategories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DishesController.cls
public with sharing class DishesController {
    @AuraEnabled(cacheable=true)
    public static List<Dish__c> getMenu() {
        List<Dish__c> dishes;

        try{
            dishes = [SELECT 	Title__c, Price__c, Description__c, Category__c, Subcategory__c
                      FROM Dish__c];
        } catch (System.QueryException queryException) {
            dishes = new List<Dish__c>();
        }

        return dishes;
    }
}