force-app/main/default/objects/Dish__c/Dish__c.object-meta.xml
<CustomObject>
    <label>Dish</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Dish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dish__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DishCategories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dish__c/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>Subcategory</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>DishSubcategories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dish_Order__c/Dish_Order__c.object-meta.xml
<CustomObject>
    <label>Dish Order</label>
    <nameField>
        <label>Dish Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dish Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Dish__c.field-meta.xml
<CustomField>
    <fullName>Dish__c</fullName>
    <label>Dish</label>
    <referenceTo>Dish__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Dish_Order__c.field-meta.xml
<CustomField>
    <fullName>Dish_Order__c</fullName>
    <label>Dish Order</label>
    <referenceTo>Dish_Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/DishCategories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Garnishes</fullName>
    </customValue>
    <customValue>
        <fullName>Main course</fullName>
    </customValue>
    <customValue>
        <fullName>Desserts</fullName>
    </customValue>
    <customValue>
        <fullName>Snacks</fullName>
    </customValue>
    <customValue>
        <fullName>Meaty</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable</fullName>
    </customValue>
    <customValue>
        <fullName>Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Soups</fullName>
    </customValue>
    <customValue>
        <fullName>Drinks</fullName>
    </customValue>
    <masterLabel>DishCategories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DishSubcategories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bread</fullName>
    </customValue>
    <customValue>
        <fullName>Biscuits</fullName>
    </customValue>
    <customValue>
        <fullName>Muffins</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable garnish</fullName>
    </customValue>
    <customValue>
        <fullName>Cereal garnish</fullName>
    </customValue>
    <customValue>
        <fullName>Fried dishes</fullName>
    </customValue>
    <customValue>
        <fullName>Stews dishes</fullName>
    </customValue>
    <customValue>
        <fullName>Baked dishes</fullName>
    </customValue>
    <customValue>
        <fullName>Sandwiches</fullName>
    </customValue>
    <customValue>
        <fullName>Paste</fullName>
    </customValue>
    <customValue>
        <fullName>Caviar</fullName>
    </customValue>
    <customValue>
        <fullName>Sneeks</fullName>
    </customValue>
    <customValue>
        <fullName>Canape</fullName>
    </customValue>
    <customValue>
        <fullName>Tartlets</fullName>
    </customValue>
    <customValue>
        <fullName>Threads</fullName>
    </customValue>
    <customValue>
        <fullName>Pickles</fullName>
    </customValue>
    <customValue>
        <fullName>Beef</fullName>
    </customValue>
    <customValue>
        <fullName>Chicken</fullName>
    </customValue>
    <customValue>
        <fullName>Pork</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Fried</fullName>
    </customValue>
    <customValue>
        <fullName>Boiled</fullName>
    </customValue>
    <customValue>
        <fullName>Stewed</fullName>
    </customValue>
    <customValue>
        <fullName>River fish</fullName>
    </customValue>
    <customValue>
        <fullName>Sea fish</fullName>
    </customValue>
    <customValue>
        <fullName>Seafood</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable</fullName>
    </customValue>
    <customValue>
        <fullName>Meaty</fullName>
    </customValue>
    <customValue>
        <fullName>Lungs</fullName>
    </customValue>
    <customValue>
        <fullName>Hot</fullName>
    </customValue>
    <masterLabel>DishSubcategories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DishOrderItemControllerTest.cls
@IsTest
public with sharing class DishOrderItemControllerTest {

    public static String OPEN_STATUS = 'Open';

    public static String TEST_DISH_NAME = 'Test dish';
    public static String TEST_DISH_CATEGORY = 'Bakery';
    public static String TEST_DISH_SUBCATEGORY = 'Bread';
    public static Decimal TEST_PRICE = 1.0;

    public static String EXPECTED_NO_ITEMS = 'Actual amount of order items does not equal to excpected. (Expected 0)';
    public static String INVALID_AMOUNT = 'Actual amount of order items does not equal to excpected';
    public static String INVALID_ID = 'Actual id of order items does not equal to excpected';

    @TestSetup
    static void makeData(){
        Dish_Order__c order = new Dish_Order__c(Status__c = OPEN_STATUS);

        insert order;

        Dish__c dish = new Dish__c(Title__c = TEST_DISH_NAME,
                                       Category__c = TEST_DISH_CATEGORY,
                                       Subcategory__c = TEST_DISH_SUBCATEGORY,
                                       Price__c = TEST_PRICE);

        insert dish;
    }

    @IsTest
    public static void getOrderItemsByOrderIdEmpty() {

        Dish_Order__c order = [SELECT Name FROM Dish_Order__c WHERE Status__c = 'Open' LIMIT 1];

        List<Order_Item__c> items;
        
        try {
            items = DishOrderItemController.getOrderItemsByOrderId(order.Id);
        } catch (System.QueryException queryException) {
            System.assertEquals(queryException.getMessage(), queryException.getMessage());
        }

        System.assertEquals(0, items.size(), EXPECTED_NO_ITEMS);

    }

    @IsTest
    public static void getOrderItemsByOrderId() {

        Dish_Order__c order = [SELECT Name FROM Dish_Order__c WHERE Status__c = 'Open' LIMIT 1];

        Dish__c dish = [SELECT Name FROM Dish__c LIMIT 1];


        Integer length = 5;
        List<Order_Item__c> items = new List<Order_Item__c>();

        for(Integer i = 1; i <= length; i++) {
            Order_Item__c orderItem = new Order_Item__c(Dish__c = dish.Id,
                                                        Amount__c = 1,
                                                        Dish_Order__c = order.Id);
            items.add(orderItem);
        }

        insert items;

        List<Order_Item__c> resultItems = DishOrderItemController.getOrderItemsByOrderId(order.Id);

        System.assertEquals(length, resultItems.size(), EXPECTED_NO_ITEMS);
    }

    @IsTest
    public static void getOrderItemByIdTest() {

        Dish_Order__c order = [SELECT Name FROM Dish_Order__c WHERE Status__c = 'Open' LIMIT 1];

        Dish__c dish = [SELECT Name FROM Dish__c LIMIT 1];

        Order_Item__c orderItem = new Order_Item__c(Dish__c = dish.Id,
                                                        Amount__c = 1,
                                                        Dish_Order__c = order.Id);

        insert orderItem;

        Order_Item__c resultOrderItem = DishOrderItemController.getOrderItemById(orderItem.Id);

        System.assertEquals(orderItem.Id, resultOrderItem.Id, INVALID_ID);
    }
}